#!/usr/bin/env ansible-playbook
---
- name: Webserver installed on web fleet
  hosts: app_web
  tags:
    - app
  tasks:
    - name: Packages installed
      tags:
        - packages
      loop:
        - nginx
        - certbot
      package:
        name: "{{ item }}"
        state: present
